// SPDX-License-Identifier: GPL-3.0-or-later
package org.walktalkmeditate.pilgrim.data.pilgrim.builder

import org.walktalkmeditate.pilgrim.data.entity.ActivityInterval
import org.walktalkmeditate.pilgrim.data.entity.RouteDataSample
import org.walktalkmeditate.pilgrim.data.entity.VoiceRecording
import org.walktalkmeditate.pilgrim.data.entity.Walk
import org.walktalkmeditate.pilgrim.data.entity.WalkEvent
import org.walktalkmeditate.pilgrim.data.entity.Waypoint

/**
 * Pre-Room-insert bundle: a Walk + its child entities, all with
 * `walkId = 0L` placeholder. The importer runs the actual inserts
 * inside a `database.withTransaction { ... }`, captures the
 * autoGenerated `walk.id`, and rewrites each child entity's `walkId`
 * before bulk-inserting.
 *
 * No `AltitudeSample` field — Android-side WalkPhoto lat/lng/altitude
 * round-trip via the GeoJSON LineString's z-coordinate. iOS exports
 * altitude per-sample inside the LineString; the importer extracts
 * those into RouteDataSample rows directly. We don't reconstruct
 * AltitudeSample rows on import (they were a barometric-precision
 * stream, not a route sample stream — losing them is acceptable).
 */
data class PendingImport(
    val walk: Walk,
    val routeSamples: List<RouteDataSample>,
    val walkEvents: List<WalkEvent>,
    val activityIntervals: List<ActivityInterval>,
    val waypoints: List<Waypoint>,
    val voiceRecordings: List<VoiceRecording>,
    val walkPhotos: List<PendingWalkPhoto>,
)

/**
 * Pre-Room-insert wire shape for `WalkPhoto`. Carries the same
 * fields without the Stage 7-A `walkId > 0` invariant — the
 * importer constructs the real `WalkPhoto` after capturing the
 * autoGenerated walk id.
 */
data class PendingWalkPhoto(
    val photoUri: String,
    val pinnedAt: Long,
    val takenAt: Long?,
)
